/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//port mode register
#define GPIOD_MODER 0x40020C00U
//port output type register
#define GPIOD_OTYPER 0x40020C04U
//port output speed register
#define GPIOD_OSPEEDR 0x40020C08U
//port pullup pulldown register
#define GPIOD_PUPDR 0x40020C0CU
//port output data register
#define GPIOD_ODR 0x40020C14U

#include <stddef.h>
#include <stdint.h>

void delay(void) {
	for(volatile uint32_t i = 0; i < 500000; i++);
}

int main(void)
{
	//Set enable bit for PortD
	*((volatile uint32_t*)(0x40023800U + 0x30U)) |= (1<<3);
	//Set PIN15 of PortD as output -> 01 for output
	*((volatile uint32_t*)(GPIOD_MODER)) |= (1<<30);
	*((volatile uint32_t*)(GPIOD_MODER)) &= ~(1<<31);
	//Set Output type as push-pull
	*((volatile uint32_t*)(GPIOD_OTYPER)) &= ~(1<<15);
	//Set the speed to slow, should be 2MHz-8MHz
	*((volatile uint32_t*)(GPIOD_OSPEEDR)) &= ~(1<<30) && ~(1<<31);
	//*((volatile uint32_t*)(GPIOD_MODER)) &= ~(1<<31);
	//Disable PullUp PullDown, we dont need it for leds
	*((volatile uint32_t*)(GPIOD_PUPDR)) &= ~(1<<30) && ~(1<<31);

	while(1){
		//Switch led15 on
		*((volatile uint32_t*)(GPIOD_ODR)) |= (1<<15);
		delay();
		//Swtich led15 off
		*((volatile uint32_t*)(GPIOD_ODR)) &= ~(1<<15);
		delay();
	}
}
